#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import random
import sys
import os

deck = [ ' 1', ' 2', ' 3', ' 4', ' 5', ' 6', ' 7', ' 8',
    ' 9', '10', '11', '12', '13', '14', '15', '16', '17',
    '18', '19', '20', '21', '22', '23', '24', '25', '26',
    '27', '28', '29', '30', '31', '32', '33', '34', '35',
    '36' ]

usage = '''Usage: lenormand [ARG]

where [ARG] can be any digit from 1 to 36. This number equals the amount of
Lenormand cards to be dealt. If no argument is given, three cards are dealt.

If argument is -h, then this usage and card names are shown.

Card names:

1 - Rider\t11 - Whip\t21 - Mountain\t31 - Sun
2 - Clover\t12 - Birds\t22 - Crossroads\t32 - Moon
3 - Ship\t13 - Child\t23 - Mice\t33 - Key
4 - House\t14 - Fox\t24 - Heart\t34 - Fish
5 - Tree\t15 - Bear\t25 - Ring\t35 - Anchor
6 - Clouds\t16 - Stars\t26 - Book\t36 - Cross
7 - Snake\t17 - Stork\t27 - Letter
8 - Coffin\t18 - Dog\t28 - Man
9 - Bouquet\t19 - Tower\t29 - Woman
10 - Scythe\t20 - Garden\t30 - Lilies\n'''

random.shuffle(deck)

def output_and_exit(count):

    i = count

    # 6 (3+3) Card layout
    if count == 6:
        while i > 0:
            print deck.pop(),
            print deck.pop(),
            print deck.pop()

            i = i - 3

        sys.exit()

    # 9 Card Layout
    if count == 9:
        while i > 0:
            print deck.pop(),
            print deck.pop(),
            print deck.pop()

            i = i - 3

        sys.exit()

    # 4*8+4 Grand Tableau
    if count == 36:
        while i > 4:
            print deck.pop(),
            print deck.pop(),
            print deck.pop(),
            print deck.pop(),
            print deck.pop(),
            print deck.pop(),
            print deck.pop(),
            print deck.pop()

            i = i - 8
        print "     ",
        print deck.pop(),
        print deck.pop(),
        print deck.pop(),
        print deck.pop()

        sys.exit()

    while i > 0:
        print deck.pop(),

        i = i - 1

    sys.exit()

def main():

    min_value = 1
    max_value = 36

    # Deal three cards by default
    value = 3

    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print usage
        sys.exit()

    if len(sys.argv) == 2:
        try:
            value = int(sys.argv[1])
        except ValueError:
            print "Valid values: 1-36"
            sys.exit(1)

        if value < min_value or value > max_value:
            print "Valid values: 1-36"
            sys.exit(1)
        else:
            output_and_exit(value)

    output_and_exit(value)

if __name__ == "__main__":
    main()

