#!/usr/bin/env bash

# update-vim-plugins runs "git pull" in every Vim plugin directory. It uses
# Vim's native package loading system. Edit PLUGIN_DIR variable accordingly.

PLUGIN_DIR="$HOME/.vim/pack/plugins"

update() {
    local i
    for i in $(find "$1" -type d -name ".git" | cut -d"/" -f-2); do
        cd "$i"
        echo "\$ git pull $i"
        git pull
        cd "$PLUGIN_DIR"
    done
}

cd "$PLUGIN_DIR"

[ -d "start" ] && update "start" || echo "No start directory found."
[ -d "opt" ] && update "opt" || echo "No opt directory found."

